version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: rag_qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    container_name: rag_ollama
    restart: unless-stopped
    environment:
      - OLLAMA_NUM_PARALLEL=${OLLAMA_NUM_PARALLEL:-2}
      - OLLAMA_MAX_LOADED_MODELS=${OLLAMA_MAX_LOADED_MODELS:-2}
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    # If no GPU is present, Ollama will run on CPU automatically.

  rag:
    build:
      context: ./rag_service
      dockerfile: Dockerfile
    container_name: rag_service
    restart: unless-stopped
    depends_on:
      - qdrant
      - ollama
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - QDRANT_URL=${QDRANT_URL:-http://qdrant:6333}
      - CONFIG_PATH=${CONFIG_PATH:-/config/config.yaml}
    ports:
      - "8000:8000"
    volumes:
      - ./config:/config
      - ./data/docs:/data/docs

volumes:
  qdrant_storage:
  ollama_models:
